# Generated by Django 5.2.7 on 2026-03-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('resumes', '0005_resume_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('user_user', '用户聊天'), ('user_ai', 'AI 简历对话')], db_index=True, default='user_user', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='resume',
            field=models.ForeignKey(blank=True, help_text='关联的简历（仅 AI 简历对话时使用）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='存储 AI 对话的额外信息（如 instructions、intent、resume_snapshot 等）'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('voice', '语音'), ('video', '视频'), ('ai_instruction', 'AI 更新指令')], default='text', max_length=20),
        ),
    ]
