"""
Django settings for ai_interview_backend project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
#后台管理地址：http://localhost:8000/admin/
#接口文档地址：http://127.0.0.1:8000/api/v1/schema/swagger-ui/
import os
from pathlib import Path
from dotenv import load_dotenv # 添加这一行

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env')) # 添加这一行，加载 .env 文件
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')


# Application definition

INSTALLED_APPS = [
    'channels',
    'simpleui',  # 【核心新增】将 simpleui 放在第一行
    'drf_spectacular',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    # 3rd party apps
    'rest_framework',
    'django.contrib.sites',  # allauth 需要这个
    'allauth',  # allauth 核心
    'allauth.account',  # allauth 账户管理
    'allauth.socialaccount',  # allauth 第三方账户
    'allauth.socialaccount.providers.github',  # GitHub 提供商
    'dj_rest_auth',  # 新增
    'dj_rest_auth.registration',  # 新增
    'django_filters',
    # Local apps
    'users',
    'resumes',
    'interviews',
    'reports',
    'system',
    'blog',
    'interactions',
    'notifications',
   'chat',
    'django_extensions',
]

# 3. 将应用的入口指向 Channels 的 ASGI application
ASGI_APPLICATION = 'ai_interview_backend.asgi.application'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 【核心修正】添加 allauth 的中间件
    # 官方建议将它放在 AuthenticationMiddleware 之后
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'ai_interview_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_interview_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# 【核心新增】The absolute path to the directory where collectstatic will collect static files for deployment.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# 指定自定义的用户模型
AUTH_USER_MODEL = 'users.User'


# Django REST Framework 配置
REST_FRAMEWORK = {
    # 默认的权限策略：除非明确指定，否则所有接口都需要认证
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 默认的认证方案：使用 JWT
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    #添加这一行来全局启用分页
    'DEFAULT_PAGINATION_CLASS': 'system.pagination.StandardResultsSetPagination',
# 【核心新增】告诉 DRF 使用 spectacular 来生成 API schema
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Simple JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),    # Access Token 有效期
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),     # Refresh Token 有效期
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": True, # 登录后更新 last_login 字段

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY, # 使用 Django 的 SECRET_KEY
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    # 自定义 Token Claims，如果需要的话
    # 'TOKEN_OBTAIN_SERIALIZER': 'path.to.MyTokenObtainPairSerializer',
}

# CORS 配置
# --- CORS CONFIGURATION (Final Version) ---
#
# 允许所有来源（开发时方便，生产环境请使用下面的白名单）
CORS_ALLOW_ALL_ORIGINS = False  # 生产环境绝不能允许所有
CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', '').split(',')
# 确保 CSRF 信任我们的前端来源
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
# 或者使用更安全的白名单模式
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
# ]

# # 确保 CSRF 信任我们的前端来源
# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:5173',
#     'http://127.0.0.1:5173',
# ]


# ---------------- MEDIA FILES CONFIGURATION ----------------
#
# MEDIA_URL: 访问上传文件的 URL 前缀 (必须以斜杠结尾)
# 例如: http://localhost:8000/media/resumes/my_resume.pdf
MEDIA_URL = '/media/'

# MEDIA_ROOT: 上传文件在服务器上存储的物理根目录
# os.path.join(BASE_DIR, 'media') 会在你的项目根目录下创建一个名为 'media' 的文件夹
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ---------------- CACHES CONFIGURATION ----------------
REDIS_HOST = os.getenv('REDIS_HOST', '127.0.0.1')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}/1", # 使用 Redis 的 1 号数据库
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        "TIMEOUT": 3600 # 默认缓存超时时间 (1小时)
    }
}

# --- EMAIL SETTINGS ---
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# 默认发件人地址
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# --- ALLAUTH CONFIGURATION (Final SPA Version) ---
AUTH_USER_MODEL = 'users.User'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
SITE_ID = 1
# 【核心修正】指定使用我们自定义的 SocialAccountAdapter
SOCIALACCOUNT_ADAPTER = 'users.adapter.CustomSocialAccountAdapter'
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
ACCOUNT_LOGIN_METHOD = "email"
ACCOUNT_SIGNUP_METHODS = ["email"]
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_PROVIDERS = {
    'github': { 'SCOPE': [ 'user:email' ] }
}

# --- DJ-REST-AUTH CONFIGURATION (保持不变) ---
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,
    'TOKEN_MODEL': None,
}

# --- CELERY SETTINGS ---
# 指定消息中间件(Broker)的地址，我们使用 Redis 的 2 号数据库
# # 避免与缓存使用的 1 号数据库冲突
# CELERY_BROKER_URL = 'redis://127.0.0.1:6379/2'
# 添加 RabbitMQ 的配置
# amqp://guest:guest@localhost:5672// 是 RabbitMQ 的默认连接地址

RABBITMQ_HOST = os.getenv('RABBITMQ_HOST', 'localhost')

CELERY_BROKER_URL = f'amqp://guest:guest@{RABBITMQ_HOST}:5672//'
# 指定结果后端(Result Backend)的地址，用于存储任务执行结果
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/2"
# 接受的内容类型
CELERY_ACCEPT_CONTENT = ['json']
# 任务序列化方式
CELERY_TASK_SERIALIZER = 'json'
# 结果序列化方式
CELERY_RESULT_SERIALIZER = 'json'
# Celery 使用的时区
CELERY_TIMEZONE = 'UTC' # 与 Django 的 TIME_ZONE 保持一致

# --- CELERY BEAT SETTINGS (定时任务调度器) ---
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # 任务名称，可以任意取
    'cleanup-stale-interviews-every-30-minutes': {
        # 指向我们刚刚创建的任务，格式为: 'app_name.tasks.task_function_name'
        'task': 'interviews.tasks.cleanup_stale_interviews',
        # 'schedule': crontab(minute='*/30'), # 每30分钟执行一次
        'schedule': 900, # 为简单起见，我们也可以设置为每 900秒执行一次
    },
    'record-daily-post-stats-nightly': {
        'task': 'blog.tasks.record_daily_stats',
        'schedule': crontab(hour=23, minute=50),  # 每天晚上 23:50 执行
    },
}
#celery -A ai_interview_backend worker -l info -P gevent
# celery -A ai_interview_backend beat -l info

# 4. 配置 Channel Layer，使用 Redis
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # 【核心修改】使用 redis://host:port/db 的格式
            # 注意：这里假设您的 REDIS_HOST 和 REDIS_PORT 变量已经定义好了
            "hosts": [f"redis://{REDIS_HOST}:{REDIS_PORT}/3"],
        },
    },
}