# Generated by Django 5.2.7 on 2026-05-21 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('interview_started', '面试开始'), ('interview_completed', '面试完成'), ('interview_aborted', '面试异常退出'), ('resume_exported', '简历导出'), ('resume_diagnosed', '简历诊断'), ('resume_generated', '简历生成'), ('resume_saved', '简历发布'), ('report_generated', '报告生成')], max_length=50, verbose_name='操作类型')),
                ('action_status', models.CharField(choices=[('success', '成功'), ('warning', '警告'), ('error', '错误')], default='success', max_length=20, verbose_name='操作状态')),
                ('action_data', models.JSONField(blank=True, default=dict, verbose_name='操作数据')),
                ('resource_type', models.CharField(choices=[('interview', '面试'), ('resume', '简历'), ('report', '报告')], max_length=20, verbose_name='资源类型')),
                ('resource_id', models.CharField(blank=True, default='', max_length=255, verbose_name='资源ID')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
